script:
    - echo TRAVIS_COMMIT $TRAVIS_COMMIT
    - echo TRAVIS_BRANCH $TRAVIS_BRANCH
    - echo TRAVIS_TAG $TRAVIS_TAG
    - echo TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST
    - echo TRAVIS_PULL_REQUEST_SHA $TRAVIS_PULL_REQUEST_SHA
    - echo TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_BRANCH
    - git show-ref
    - git ls-remote origin
notifications:
  slack:
    template: "deploying $TRAVIS_BRANCH to %{branch}"
    rooms:
      secure: oQjSjVuOky0GQiFdTs0RsgMEXYdt0fusUECLW1f7D25Uykcv2Nn6wn+tkw65waBzk7hYe6vcTXGbECsgC3igZHVaG9qRO/4H4JsOlllXLcX9j4llKluq+AzK9ocbpan6lSGy+wLTlNmhPlGKBf+kySYL/oBYKvHSQ1RPgVhbUCWeW8QPjKuRzjxA4ce73cSFffFZBiwJ7C2/eArxxqXXmYPI6zF79nn8TC/WuwSJ7k2NBaLTuHguUNEpeg5tA2DFi1xJx62Xn3Kni19ZNSdv1OAL+zupBU1NMVFlufUG8shBX62ogIIefAOIUqxB29n5Qxvyq7sAfme6jDchwUGU1o113EsrtSeicF8wZ9EW+lqfvt8Zgn00hPUYNEaZrwSKZNTSLgNf8P6lt0GN4YQOarbLS8VcVD4sZmPDE/+vSVQ3rkBNSq98j/0865LqdLxY1dedDLG4i+TUVQj1ijuBVvgyvZ7uiHCVDqzFVZdwo7FLP9Pfg2qhIfvicEYrG8PLulerGWTOaJ76zaesgsNfSNT+pDGyG1jlA4ZdTbZJLBS+FYuHuQLSvKfvujKy6II0YJ0ezoWjymAqkW/81J5qtzXRfG2s0yeAHZvtj4wBfqdwyKLMnujB2kCwPsYTt7t46zHhM/hEdPxQSkEn/CbkWd2XUY7CZLX3jqOThYLM2vo=
