env:
    global:
        - BRANCH_REF=$(git ls-remote -q --heads | grep $TRAVIS_COMMIT | cut -f2)
        - IS_VISTA=$(git ls-remote -q --heads | grep $TRAVIS_COMMIT | grep refs/heads/vista)
        - IS_RELEASE=$( [[ "$IS_VISTA" && "$TRAVIS_TAG" ]] && echo true )
        - VAR_A=$(./buildenv.sh)
script:
    - echo VAR_A $VAR_A
    - echo VAR_B $VAR_B
    - echo VAR_C $VAR_C
    - echo IS_RELEASE $IS_RELEASE
    - echo BRANCH_REF $BRANCH_REF
    - echo IS_VISTA $IS_VISTA
    - echo TRAVIS_COMMIT $TRAVIS_COMMIT
    - echo TRAVIS_BRANCH $TRAVIS_BRANCH
    - echo TRAVIS_TAG $TRAVIS_TAG
    - echo TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST
    - echo TRAVIS_PULL_REQUEST_SHA $TRAVIS_PULL_REQUEST_SHA
    - echo TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_BRANCH
    - git show-ref
    - git ls-remote origin
    - git ls-remote origin | grep $TRAVIS_COMMIT
    - if [[ "$IS_VISTA" ]]; then echo is vista; fi
    - if [[ "$IS_RELEASE" ]]; then echo release; fi
